fonts = [
    [0,0,"LiberationMono-BoldItalic"],
    [0,0,"LiberationMono-Italic"],
    [0,0,"LiberationMono"],
    [0,0,"LiberationMono-Bold"],
    ["!Paul Maul", "Regular", "!PaulMaul", 1, 6, "fs/PaulMaul/0"],
    ["!Paul Maul", "Bold", "!PaulMaul-Bold", 1, 6, "fs/PaulMaul/1"],
    ["1942 report", "1942 report", "1942report", 0, 17, "fs/1942-report/0"],
    ["20 db", "Regular", "20db", 8, 4, "fs/20-db/0"],
    ["2Dumb", "Regular", "2Dumb", 1, 8, "fs/3dumb/1"],
    ["3Dumb", "Regular", "3dumb", 0, 8, "fs/3dumb/0"],
    ["ABeeZee", "Italic", "ABeeZee-Italic", 1, 12, "fs/abeezee/1"],
    ["ABeeZee", "Regular", "ABeeZee-Regular", 1, 12, "fs/abeezee/0"],
    ["Aaargh", "Normal", "AaarghNormal", 0, 12, "fs/Aaargh/0"],
    ["Aganè", "Regular", "Aan55", 1, 12, "fs/agane/1"],
    ["Abel", "Regular", "Abel-Regular", 1, 12, "fs/abel/0"],
    ["Abhaya Libre", "Bold", "AbhayaLibre-Bold", 1, 14, "fs/abhaya-libre/3"],
    ["Abhaya Libre", "ExtraBold", "AbhayaLibre-ExtraBold", 1, 14, "fs/abhaya-libre/4"],
    ["Abhaya Libre", "Medium", "AbhayaLibre-Medium", 1, 14, "fs/abhaya-libre/1"],
    ["Abhaya Libre", "Regular", "AbhayaLibre-Regular", 1, 14, "fs/abhaya-libre/0"],
    ["Abhaya Libre", "SemiBold", "AbhayaLibre-SemiBold", 1, 14, "fs/abhaya-libre/2"],
    ["Abril Fatface", "Regular", "AbrilFatface-Regular", 3, 4, "fs/abril-fatface/0"],
    ["Acknowledgement", "Medium", "Acknowledgement", 1, 4, "fs/Acknowledgement/0"],
    ["Acme", "Regular", "Acme-Regular", 1, 12, "fs/acme/0"],
    ["Action Man", "Regular", "ActionMan", 1, 2, "fs/Action-Man/0"],
    ["Action Man", "Bold", "ActionMan-Bold", 1, 2, "fs/Action-Man/2"],
    ["Action Man", "Bold Italic", "ActionMan-BoldItalic", 1, 2, "fs/Action-Man/3"],
    ["Action Man", "Italic", "ActionMan-Italic", 1, 2, "fs/Action-Man/1"],
    ["Action Man Extended", "Regular", "ActionManExtended", 1, 2, "fs/Action-Man/6"],
    ["Action Man Extended", "Bold", "ActionManExtended-Bold", 1, 2, "fs/Action-Man/8"],
    [
        "Action Man Extended",
        "Bold Italic",
        "ActionManExtended-BoldItalic",
        1,
        2,
        "fs/Action-Man/9",
    ],
    [
        "Action Man Extended",
        "Italic",
        "ActionManExtended-Italic",
        1,
        2,
        "fs/Action-Man/7",
    ],
    ["Action Man Shaded", "Regular", "ActionManShaded", 1, 2, "fs/Action-Man/4"],
    ["Action Man Shaded", "Italic", "ActionManShaded-Italic", 1, 2, "fs/Action-Man/5"],
    [
        "Adhesive Nr. Seven",
        "Regular",
        "AdhesiveNrSevenBanners",
        0,
        3,
        "fs/Adhesive-Nr.-Seven/0",
    ],
    ["Advent Pro", "Bold", "AdventPro-Bold", 7, 12, "fs/advent-pro/6"],
    ["Advent Pro", "ExtraLight", "AdventPro-ExtraLight", 7, 12, "fs/advent-pro/1"],
    ["Advent Pro", "Light", "AdventPro-Light", 7, 12, "fs/advent-pro/2"],
    ["Advent Pro", "Medium", "AdventPro-Medium", 7, 12, "fs/advent-pro/4"],
    ["Advent Pro", "Regular", "AdventPro-Regular", 7, 12, "fs/advent-pro/3"],
    ["Advent Pro", "SemiBold", "AdventPro-SemiBold", 7, 12, "fs/advent-pro/5"],
    ["Advent Pro", "Thin", "AdventPro-Thin", 7, 12, "fs/advent-pro/0"],
    ["Afta sans", "Regular", "Aftasans", 1, 12, "fs/afta-sans/1"],
    ["Afta sans", "Italic", "Aftasans-Italic", 1, 12, "fs/afta-sans/0"],
    ["Afta serif", "Regular", "Aftaserif", 1, 14, "fs/afta-serif/0"],
    ["Afta serif", "Italic", "Aftaserif-Italic", 1, 14, "fs/afta-serif/1"],
    ["After Shok", "Regular", "AfterShok", 0, 4, "fs/After-Shok/0"],
    ["Aganè", "Light", "Agan45", 1, 12, "fs/agane/0"],
    ["Aganè", "Bold", "Agan65", 1, 12, "fs/agane/2"],
    ["Aganè", "Extra Bold", "Agan75", 1, 12, "fs/agane/3"],
    ["Aganè S", "Regular", "AganS55", 1, 12, "fs/agane/4"],
    ["Aganè S", "Bold", "AganS65", 1, 12, "fs/agane/5"],
    ["Aganè S", "Extra Bold", "AganS75", 1, 12, "fs/agane/6"],
    [
        "Aguafina Script",
        "Regular",
        "AguafinaScript-Regular",
        1,
        13,
        "fs/aguafina-script/0",
    ],
    ["Aileron", "Black", "Aileron-Black", 3, 12, "fs/aileron/14"],
    ["Aileron", "Black Italic", "Aileron-BlackItalic", 3, 12, "fs/aileron/15"],
    ["Aileron", "Bold", "Aileron-Bold", 3, 12, "fs/aileron/10"],
    ["Aileron", "Bold Italic", "Aileron-BoldItalic", 3, 12, "fs/aileron/11"],
    ["Aileron", "Heavy", "Aileron-Heavy", 3, 12, "fs/aileron/12"],
    ["Aileron", "Heavy Italic", "Aileron-HeavyItalic", 3, 12, "fs/aileron/13"],
    ["Aileron", "Italic", "Aileron-Italic", 3, 12, "fs/aileron/7"],
    ["Aileron", "Light", "Aileron-Light", 3, 12, "fs/aileron/4"],
    ["Aileron", "Light Italic", "Aileron-LightItalic", 3, 12, "fs/aileron/5"],
    ["Aileron", "Regular", "Aileron-Regular", 3, 12, "fs/aileron/6"],
    ["Aileron", "SemiBold", "Aileron-SemiBold", 3, 12, "fs/aileron/8"],
    ["Aileron", "SemiBold Italic", "Aileron-SemiBoldItalic", 3, 12, "fs/aileron/9"],
    ["Aileron", "Thin", "Aileron-Thin", 3, 12, "fs/aileron/2"],
    ["Aileron", "Thin Italic", "Aileron-ThinItalic", 3, 12, "fs/aileron/3"],
    ["Aileron", "UltraLight", "Aileron-UltraLight", 3, 12, "fs/aileron/0"],
    ["Aileron", "UltraLight Italic", "Aileron-UltraLightItalic", 3, 12, "fs/aileron/1"],
    ["Air America", "Regular", "AirAmerica-Regular", 1, 4, "fs/air-america/0"],
    ["Airstream", "Regular", "Airstream", 1, 11, "fs/Airstream/0"],
    ["Alef", "Bold", "Alef-Bold", 19, 12, "fs/alef/1"],
    ["Alef", "Regular", "Alef-Regular", 19, 12, "fs/alef/0"],
    ["Alegreya", "Black", "Alegreya-Black", 3, 14, "fs/alegreya/4"],
    ["Alegreya", "Black Italic", "Alegreya-BlackItalic", 3, 14, "fs/alegreya/5"],
    ["Alegreya", "Bold", "Alegreya-Bold", 3, 14, "fs/alegreya/2"],
    ["Alegreya", "Bold Italic", "Alegreya-BoldItalic", 3, 14, "fs/alegreya/3"],
    ["Alegreya", "Italic", "Alegreya-Italic", 3, 14, "fs/alegreya/1"],
    ["Alegreya", "Regular", "Alegreya-Regular", 3, 14, "fs/alegreya/0"],
    ["Alegreya SC", "Black", "AlegreyaSC-Black", 3, 14, "fs/alegreya/10"],
    ["Alegreya SC", "Black Italic", "AlegreyaSC-BlackItalic", 3, 14, "fs/alegreya/11"],
    ["Alegreya SC", "Bold", "AlegreyaSC-Bold", 3, 14, "fs/alegreya/8"],
    ["Alegreya SC", "Bold Italic", "AlegreyaSC-BoldItalic", 3, 14, "fs/alegreya/9"],
    ["Alegreya SC", "Italic", "AlegreyaSC-Italic", 3, 14, "fs/alegreya/7"],
    ["Alegreya SC", "Regular", "AlegreyaSC-Regular", 3, 14, "fs/alegreya/6"],
    ["Alegreya Sans", "Black", "AlegreyaSans-Black", 3, 12, "fs/alegreya-sans/12"],
    [
        "Alegreya Sans",
        "Black Italic",
        "AlegreyaSans-BlackItalic",
        3,
        12,
        "fs/alegreya-sans/13",
    ],
    ["Alegreya Sans", "Bold", "AlegreyaSans-Bold", 3, 12, "fs/alegreya-sans/8"],
    [
        "Alegreya Sans",
        "Bold Italic",
        "AlegreyaSans-BoldItalic",
        3,
        12,
        "fs/alegreya-sans/9",
    ],
    [
        "Alegreya Sans",
        "ExtraBold",
        "AlegreyaSans-ExtraBold",
        3,
        12,
        "fs/alegreya-sans/10",
    ],
    [
        "Alegreya Sans",
        "ExtraBold Italic",
        "AlegreyaSans-ExtraBoldItalic",
        3,
        12,
        "fs/alegreya-sans/11",
    ],
    ["Alegreya Sans", "Italic", "AlegreyaSans-Italic", 3, 12, "fs/alegreya-sans/5"],
    ["Alegreya Sans", "Light", "AlegreyaSans-Light", 3, 12, "fs/alegreya-sans/2"],
    [
        "Alegreya Sans",
        "Light Italic",
        "AlegreyaSans-LightItalic",
        3,
        12,
        "fs/alegreya-sans/3",
    ],
    ["Alegreya Sans", "Medium", "AlegreyaSans-Medium", 3, 12, "fs/alegreya-sans/6"],
    [
        "Alegreya Sans",
        "Medium Italic",
        "AlegreyaSans-MediumItalic",
        3,
        12,
        "fs/alegreya-sans/7",
    ],
    ["Alegreya Sans", "Regular", "AlegreyaSans-Regular", 3, 12, "fs/alegreya-sans/4"],
    ["Alegreya Sans", "Thin", "AlegreyaSans-Thin", 3, 12, "fs/alegreya-sans/0"],
    [
        "Alegreya Sans",
        "Thin Italic",
        "AlegreyaSans-ThinItalic",
        3,
        12,
        "fs/alegreya-sans/1",
    ],
    ["Alegreya Sans SC", "Black", "AlegreyaSansSC-Black", 3, 12, "fs/alegreya-sans/26"],
    [
        "Alegreya Sans SC",
        "Black Italic",
        "AlegreyaSansSC-BlackItalic",
        3,
        12,
        "fs/alegreya-sans/27",
    ],
    ["Alegreya Sans SC", "Bold", "AlegreyaSansSC-Bold", 3, 12, "fs/alegreya-sans/22"],
    [
        "Alegreya Sans SC",
        "Bold Italic",
        "AlegreyaSansSC-BoldItalic",
        3,
        12,
        "fs/alegreya-sans/23",
    ],
    [
        "Alegreya Sans SC",
        "ExtraBold",
        "AlegreyaSansSC-ExtraBold",
        3,
        12,
        "fs/alegreya-sans/24",
    ],
    [
        "Alegreya Sans SC",
        "ExtraBold Italic",
        "AlegreyaSansSC-ExtraBoldItalic",
        3,
        12,
        "fs/alegreya-sans/25",
    ],
    [
        "Alegreya Sans SC",
        "Italic",
        "AlegreyaSansSC-Italic",
        3,
        12,
        "fs/alegreya-sans/19",
    ],
    ["Alegreya Sans SC", "Light", "AlegreyaSansSC-Light", 3, 12, "fs/alegreya-sans/16"],
    [
        "Alegreya Sans SC",
        "Light Italic",
        "AlegreyaSansSC-LightItalic",
        3,
        12,
        "fs/alegreya-sans/17",
    ],
    [
        "Alegreya Sans SC",
        "Medium",
        "AlegreyaSansSC-Medium",
        3,
        12,
        "fs/alegreya-sans/20",
    ],
    [
        "Alegreya Sans SC",
        "Medium Italic",
        "AlegreyaSansSC-MediumItalic",
        3,
        12,
        "fs/alegreya-sans/21",
    ],
    [
        "Alegreya Sans SC",
        "Regular",
        "AlegreyaSansSC-Regular",
        3,
        12,
        "fs/alegreya-sans/18",
    ],
    ["Alegreya Sans SC", "Thin", "AlegreyaSansSC-Thin", 3, 12, "fs/alegreya-sans/14"],
    [
        "Alegreya Sans SC",
        "Thin Italic",
        "AlegreyaSansSC-ThinItalic",
        3,
        12,
        "fs/alegreya-sans/15",
    ],
    ["Aleo", "Bold", "Aleo-Bold", 1, 15, "fs/aleo/4"],
    ["Aleo", "BoldItalic", "Aleo-BoldItalic", 1, 15, "fs/aleo/5"],
    ["Aleo", "Italic", "Aleo-Italic", 1, 15, "fs/aleo/3"],
    ["Aleo", "Light", "Aleo-Light", 1, 15, "fs/aleo/0"],
    ["Aleo", "LightItalic", "Aleo-LightItalic", 1, 15, "fs/aleo/1"],
    ["Aleo", "Regular", "Aleo-Regular", 1, 15, "fs/aleo/2"],
    ["Alex Brush", "Regular", "AlexBrush-Regular", 1, 13, "fs/alex-brush/0"],
    ["Alfa Slab One", "Regular", "AlfaSlabOne-Regular", 1, 4, "fs/alfa-slab/0"],
    ["Alice", "Regular", "Alice-Regular", 9, 14, "fs/alice/0"],
    ["Allura", "Regular", "Allura-Regular", 3, 13, "fs/allura/0"],
    ["Almendra", "Bold", "Almendra-Bold", 1, 4, "fs/almendra/2"],
    ["Almendra", "Bold Italic", "Almendra-BoldItalic", 1, 4, "fs/almendra/3"],
    ["Almendra", "Italic", "Almendra-Italic", 1, 4, "fs/almendra/1"],
    ["Almendra", "Regular", "Almendra-Regular", 3, 4, "fs/almendra/0"],
    ["Almendra Display", "Regular", "AlmendraDisplay-Regular", 1, 4, "fs/almendra/8"],
    ["Almendra SC", "Bold", "AlmendraSC-Bold", 1, 4, "fs/almendra/6"],
    ["Almendra SC", "Bold Italic", "AlmendraSC-BoldItalic", 1, 4, "fs/almendra/7"],
    ["Almendra SC", "Italic", "AlmendraSC-Italic", 1, 4, "fs/almendra/5"],
    ["Almendra SC", "Regular", "AlmendraSC-Regular", 1, 4, "fs/almendra/4"],
    ["Alpha Echo", "Regular", "AlphaEcho", 15, 4, "fs/Alpha-Echo/0"],
    ["Amadeus Regular", "Amadeus Regular", "Amadeus-Regular", 1, 4, "fs/Amadeus/0"],
    ["Amaranth", "Bold", "Amaranth-Bold", 1, 12, "fs/amaranth/2"],
    ["Amaranth", "Bold Italic", "Amaranth-BoldItalic", 1, 12, "fs/amaranth/3"],
    ["Amaranth", "Italic", "Amaranth-Italic", 1, 12, "fs/amaranth/1"],
    ["Amaranth", "Regular", "Amaranth-Regular", 1, 12, "fs/amaranth/0"],
    ["Amatic", "Bold", "Amatic-Bold", 3, 6, "fs/amatic/1"],
    ["Amatic SC", "Regular", "AmaticSC-Regular", 3, 6, "fs/amatic/0"],
    ["Amble", "Bold", "Amble-Bold", 3, 12, "fs/amble/4"],
    ["Amble", "Bold Italic", "Amble-BoldItalic", 3, 12, "fs/amble/5"],
    ["Amble", "Italic", "Amble-Italic", 3, 12, "fs/amble/3"],
    ["Amble", "Light", "Amble-Light", 3, 12, "fs/amble/0"],
    ["Amble", "Light Condensed", "Amble-LightCondensed", 3, 12, "fs/amble/6"],
    [
        "Amble",
        "Light Condensed Italic",
        "Amble-LightCondensedItalic",
        3,
        12,
        "fs/amble/7",
    ],
    ["Amble", "Light Italic", "Amble-LightItalic", 3, 12, "fs/amble/1"],
    ["Amble", "Regular", "Amble-Regular", 3, 12, "fs/amble/2"],
    ["Amerika", "Regular", "Amerika", 13, 4, "fs/Amerika/0"],
    ["Amerika Alternates", "Regular", "AmerikaAlternates", 0, 4, "fs/Amerika/1"],
    ["Amerika Sans", "Regular", "AmerikaSans", 1, 4, "fs/Amerika/2"],
    ["Amiko", "Bold", "Amiko-Bold", 515, 12, "fs/amiko/2"],
    ["Amiko", "Regular", "Amiko-Regular", 515, 12, "fs/amiko/0"],
    ["Amiko", "SemiBold", "Amiko-SemiBold", 515, 12, "fs/amiko/1"],
    ["Amita", "Bold", "Amita-Bold", 515, 13, "fs/amita/1"],
    ["Amita", "Regular", "Amita-Regular", 515, 13, "fs/amita/0"],
    ["Anagram", "Regular", "Anagram", 1, 11, "fs/Anagram/0"],
    ["Andada", "Bold", "Andada-Bold", 3, 14, "fs/andada/2"],
    ["Andada", "Bold Italic", "Andada-BoldItalic", 3, 14, "fs/andada/3"],
    ["Andada", "Italic", "Andada-Italic", 3, 14, "fs/andada/1"],
    ["Andada", "Regular", "Andada-Regular", 3, 14, "fs/andada/0"],
    ["Andada SC", "Bold", "AndadaSC-Bold", 3, 14, "fs/andada/6"],
    ["Andada SC", "Bold Italic", "AndadaSC-BoldItalic", 3, 14, "fs/andada/7"],
    ["Andada SC", "Italic", "AndadaSC-Italic", 3, 14, "fs/andada/5"],
    ["Andada SC", "Regular", "AndadaSC-Regular", 3, 14, "fs/andada/4"],
    ["Andika New Basic", "Bold", "AndikaNewBasic-Bold", 3, 12, "fs/andika-basic/2"],
    [
        "Andika New Basic",
        "Bold Italic",
        "AndikaNewBasic-BoldItalic",
        3,
        12,
        "fs/andika-basic/3",
    ],
    ["Andika New Basic", "Italic", "AndikaNewBasic-Italic", 3, 12, "fs/andika-basic/1"],
    [
        "Andika New Basic",
        "Regular",
        "AndikaNewBasic-Regular",
        3,
        12,
        "fs/andika-basic/0",
    ],
    ["Anonymous", "Regular", "Anonymous", 1, 7, "fs/Anonymous/0"],
    ["Anonymous Pro", "Regular", "AnonymousPro", 15, 7, "fs/Anonymous-Pro/0"],
    ["Anonymous Pro", "Bold", "AnonymousPro-Bold", 15, 7, "fs/Anonymous-Pro/2"],
    [
        "Anonymous Pro",
        "Bold Italic",
        "AnonymousPro-BoldItalic",
        15,
        7,
        "fs/Anonymous-Pro/3",
    ],
    ["Anonymous Pro", "Italic", "AnonymousPro-Italic", 15, 7, "fs/Anonymous-Pro/1"],
    ["Antic Didone", "Regular", "AnticDidone-Regular", 1, 14, "fs/antic/0"],
    ["Antic Sans", "Regular", "AnticSans", 1, 14, "fs/antic/1"],
    ["Antic Slab", "Regular", "AnticSlab", 1, 14, "fs/antic/2"],
    ["Antonio", "Bold", "Antonio-Bold", 3, 4, "fs/antonio/2"],
    ["Antonio", "Light", "Antonio-Light", 3, 4, "fs/antonio/0"],
    ["Antonio", "Regular", "Antonio-Regular", 3, 4, "fs/antonio/1"],
    ["AnuDaw", "Regular", "AnuDaw", 0, 4, "fs/AnuDaw/0"],
    ["AnuDaw", "Italic", "AnuDawItalic", 0, 4, "fs/AnuDaw/1"],
    ["AquilineTwo", "Regular", "AquilineTwo", 1, 4, "fs/Aquiline-two/0"],
    ["Arapey", "Italic", "Arapey-Italic", 1, 14, "fs/arapey/1"],
    ["Arapey", "Regular", "Arapey-Regular", 1, 14, "fs/arapey/0"],
    ["Arbutus", "Regular", "Arbutus", 3, 4, "fs/arbutus/0"],
    ["Arbutus Slab", "Regular", "ArbutusSlab-Regular", 3, 15, "fs/arbutus-slab/0"],
    ["Archistico", "Bold", "Archistico-Bold", 0, 4, "fs/archistico/1"],
    ["Archistico", "Normal", "Archistico-Normal", 0, 4, "fs/archistico/0"],
    [
        "Architects Daughter",
        "Regular",
        "ArchitectsDaughter",
        3,
        6,
        "fs/architects-daughter/0",
    ],
    ["Archivo", "Bold", "Archivo-Bold", 3, 12, "fs/archivo/6"],
    ["Archivo", "Bold Italic", "Archivo-BoldItalic", 3, 12, "fs/archivo/7"],
    ["Archivo", "Italic", "Archivo-Italic", 3, 12, "fs/archivo/1"],
    ["Archivo", "Medium", "Archivo-Medium", 3, 12, "fs/archivo/2"],
    ["Archivo", "Medium Italic", "Archivo-MediumItalic", 3, 12, "fs/archivo/3"],
    ["Archivo", "Regular", "Archivo-Regular", 3, 12, "fs/archivo/0"],
    ["Archivo", "SemiBold", "Archivo-SemiBold", 3, 12, "fs/archivo/4"],
    ["Archivo", "SemiBold Italic", "Archivo-SemiBoldItalic", 3, 12, "fs/archivo/5"],
    ["Archivo Black", "Regular", "ArchivoBlack-Regular", 3, 4, "fs/archivo-black/0"],
    ["Archivo Narrow", "Bold", "ArchivoNarrow-Bold", 3, 4, "fs/archivo-narrow/2"],
    [
        "Archivo Narrow",
        "Bold Italic",
        "ArchivoNarrow-BoldItalic",
        3,
        4,
        "fs/archivo-narrow/3",
    ],
    ["Archivo Narrow", "Italic", "ArchivoNarrow-Italic", 3, 4, "fs/archivo-narrow/1"],
    ["Archivo Narrow", "Regular", "ArchivoNarrow-Regular", 3, 4, "fs/archivo-narrow/0"],
    ["Arcon", "Regular", "Arcon-Regular", 3, 12, "fs/arcon/0"],
    ["Arcon", "Rounded-Regular", "Arcon-Rounded-Regular", 3, 12, "fs/arcon/1"],
    ["Arima Koshi", "Black", "ArimaKoshi-Black", 3, 12, "fs/arima/7"],
    ["Arima Koshi", "Bold", "ArimaKoshi-Bold", 3, 12, "fs/arima/6"],
    ["Arima Koshi", "ExtraLight", "ArimaKoshi-ExtraLight", 3, 12, "fs/arima/1"],
    ["Arima Koshi", "Light", "ArimaKoshi-Light", 3, 12, "fs/arima/2"],
    ["Arima Koshi", "Medium", "ArimaKoshi-Medium", 3, 12, "fs/arima/4"],
    ["Arima Koshi", "Regular", "ArimaKoshi-Regular", 3, 12, "fs/arima/3"],
    ["Arima Koshi", "Semi Bold", "ArimaKoshi-SemiBold", 3, 12, "fs/arima/5"],
    ["Arima Koshi", "Thin", "ArimaKoshi-Thin", 3, 12, "fs/arima/0"],
    ["Arima Madurai", "Black", "ArimaMadurai-Black", 3, 12, "fs/arima/15"],
    ["Arima Madurai", "Bold", "ArimaMadurai-Bold", 3, 12, "fs/arima/14"],
    ["Arima Madurai", "ExtraLight", "ArimaMadurai-ExtraLight", 3, 12, "fs/arima/9"],
    ["Arima Madurai", "Light", "ArimaMadurai-Light", 3, 12, "fs/arima/10"],
    ["Arima Madurai", "Medium", "ArimaMadurai-Medium", 3, 12, "fs/arima/12"],
    ["Arima Madurai", "Regular", "ArimaMadurai-Regular", 3, 12, "fs/arima/11"],
    ["Arima Madurai", "Semi Bold", "ArimaMadurai-SemiBold", 3, 12, "fs/arima/13"],
    ["Arima Madurai", "Thin", "ArimaMadurai-Thin", 3, 12, "fs/arima/8"],
    ["Arimo", "Regular", "Arimo", 31, 12, "fs/arimo/0"],
    ["Arimo", "Bold", "Arimo-Bold", 31, 12, "fs/arimo/2"],
    ["Arimo", "Bold Italic", "Arimo-BoldItalic", 31, 12, "fs/arimo/3"],
    ["Arimo", "Italic", "Arimo-Italic", 31, 12, "fs/arimo/1"],
    ["Arizonia", "Regular", "Arizonia-Regular", 1, 13, "fs/arizonia/0"],
    ["ArmWrestler", "Bold", "ArmWrestler-Bold", 1, 4, "fs/ArmWrestler/0"],
    ["Armalite Rifle", "Regular", "ArmaliteRifle", 1, 16, "fs/Armalite-Rifle/0"],
    ["Armata", "Regular", "Armata-Regular", 3, 12, "fs/armata/0"],
    ["Arsenal", "Bold", "Arsenal-Bold", 9, 12, "fs/arsenal/2"],
    ["Arsenal", "Bold Italic", "Arsenal-BoldItalic", 9, 12, "fs/arsenal/3"],
    ["Arsenal", "Italic", "Arsenal-Italic", 9, 12, "fs/arsenal/1"],
    ["Arsenal", "Regular", "Arsenal-Regular", 9, 12, "fs/arsenal/0"],
    ["DejaVu Sans", "Book", "DejaVuSans", 63, 12, "fs/dejavu-sans/1"],
    ["DejaVu Sans", "Bold", "DejaVuSans-Bold", 63, 12, "fs/dejavu-sans/3"],
    [
        "DejaVu Sans",
        "Bold Oblique",
        "DejaVuSans-BoldOblique",
        31,
        12,
        "fs/dejavu-sans/4",
    ],
    ["DejaVu Sans", "ExtraLight", "DejaVuSans-ExtraLight", 15, 12, "fs/dejavu-sans/0"],
    ["DejaVu Sans", "Oblique", "DejaVuSans-Oblique", 31, 12, "fs/dejavu-sans/2"],
    ["DejaVu Sans", "Condensed", "DejaVuSansCondensed", 63, 12, "fs/dejavu-sans/5"],
    [
        "DejaVu Sans",
        "Condensed Bold",
        "DejaVuSansCondensed-Bold",
        63,
        12,
        "fs/dejavu-sans/7",
    ],
    [
        "DejaVu Sans",
        "Condensed Bold Oblique",
        "DejaVuSansCondensed-BoldOblique",
        31,
        12,
        "fs/dejavu-sans/8",
    ],
    [
        "DejaVu Sans",
        "Condensed Oblique",
        "DejaVuSansCondensed-Oblique",
        31,
        12,
        "fs/dejavu-sans/6",
    ],
    ["DejaVu Sans Mono", "Book", "DejaVuSansMono", 15, 12, "fs/dejavu-sans-mono/0"],
    [
        "DejaVu Sans Mono",
        "Bold",
        "DejaVuSansMono-Bold",
        15,
        12,
        "fs/dejavu-sans-mono/2",
    ],
    [
        "DejaVu Sans Mono",
        "Bold Oblique",
        "DejaVuSansMono-BoldOblique",
        15,
        12,
        "fs/dejavu-sans-mono/3",
    ],
    [
        "DejaVu Sans Mono",
        "Oblique",
        "DejaVuSansMono-Oblique",
        15,
        12,
        "fs/dejavu-sans-mono/1",
    ],
    ["DejaVu Serif", "Book", "DejaVuSerif", 15, 14, "fs/dejavu-serif/0"],
    ["DejaVu Serif", "Bold", "DejaVuSerif-Bold", 15, 14, "fs/dejavu-serif/2"],
    [
        "DejaVu Serif",
        "Bold Italic",
        "DejaVuSerif-BoldItalic",
        15,
        14,
        "fs/dejavu-serif/3",
    ],
    ["DejaVu Serif", "Italic", "DejaVuSerif-Italic", 15, 14, "fs/dejavu-serif/1"],
    ["DejaVu Serif", "Condensed", "DejaVuSerifCondensed", 15, 14, "fs/dejavu-serif/4"],
    [
        "DejaVu Serif",
        "Condensed Bold",
        "DejaVuSerifCondensed-Bold",
        15,
        14,
        "fs/dejavu-serif/6",
    ],
    [
        "DejaVu Serif",
        "Condensed Bold Italic",
        "DejaVuSerifCondensed-BoldItalic",
        15,
        14,
        "fs/dejavu-serif/7",
    ],
    [
        "DejaVu Serif",
        "Condensed Italic",
        "DejaVuSerifCondensed-Italic",
        15,
        14,
        "fs/dejavu-serif/5",
    ],
]


ttf = [
    "阿里巴巴普惠体,Regular,AlibabaPuHuiTi-Regular,128,12,xin/AlibabaPuHuiTi-Regular.ttf",
    ",Light,AlibabaPuHuiTi-Light,128,12,xin/AlibabaPuHuiTi-Light.ttf",
    ",Medium,AlibabaPuHuiTi-Medium,128,12,xin/AlibabaPuHuiTi-Medium.ttf",
    ",Bold,AlibabaPuHuiTi-Bold,128,12,xin/AlibabaPuHuiTi-Bold.ttf",
    ",Heavy,AlibabaPuHuiTi-Heavy,128,12,xin/AlibabaPuHuiTi-Heavy.ttf",
    "OPPOSans字体,Regular,OPPOSans-R,128,12,xin/OPPOSans-R.ttf",
    ",Light,OPPOSans-L,128,12,xin/OPPOSans-L.ttf",
    ",Medium,OPPOSans-M,128,12,xin/OPPOSans-M.ttf",
    ",Bold,OPPOSans-B,128,12,xin/OPPOSans-B.ttf",
    ",Heavy,OPPOSans-H,128,12,xin/OPPOSans-H.ttf",
    "思源黑体,Regular,SourceHanSansSC-Regular,128,12,xin/SourceHanSansSC-Regular.ttf",
    ",ExtraLight,SourceHanSansSC-ExtraLight,128,12,xin/SourceHanSansSC-ExtraLight.ttf",
    ",Light,SourceHanSansSC-Light,128,12,xin/SourceHanSansSC-Light.ttf",
    ",Normal,SourceHanSansSC-Normal,128,12,xin/SourceHanSansSC-Normal.ttf",
    ",Bold,SourceHanSansSC-Bold,128,12,xin/SourceHanSansSC-Bold.ttf",
    ",Heavy,SourceHanSansSC-Heavy,128,12,xin/SourceHanSansSC-Heavy.ttf",
    "思源宋体,Regular,SourceHanSerifSC-Regular,128,12,xin/SourceHanSerifSC-Regular.ttf",
    ",ExtraLight,SourceHanSerifSC-ExtraLight,128,12,xin/SourceHanSerifSC-ExtraLight.ttf",
    ",Light,SourceHanSerifSC-Light,128,12,xin/SourceHanSerifSC-Light.ttf",
    ",Medium,SourceHanSerifSC-Medium,128,12,xin/SourceHanSerifSC-Medium.ttf",
    ",SemiBold,SourceHanSerifSC-SemiBold,128,12,xin/SourceHanSerifSC-SemiBold.ttf",
    ",Bold,SourceHanSerifSC-Bold,128,12,xin/SourceHanSerifSC-Bold.ttf",
    ",Heavy,SourceHanSerifSC-Heavy,128,12,xin/SourceHanSerifSC-Heavy.ttf",
    "锐字真言体,Regular,ZhenyanGB-Regular,128,12,xin/ZhenyanGB-Regular.ttf",
    "问藏书房体,Regular,WenCang-Regular,128,12,xin/WenCang-Regular.ttf",
    "站酷小薇体,Regular,xiaowei,128,12,xin/xiaowei.ttf",
    "站酷文艺体,Regular,zcoolwenyiti,128,12,xin/zcoolwenyiti.ttf",
    "站酷高端黑,Regular,zcool-gdh,128,12,xin/zcool-gdh.ttf",
    "站酷酷黑,Regular,HuXiaoBoKuHei,128,12,xin/HuXiaoBoKuHei.ttf",
    "站酷快乐体,Regular,HappyZcool-2016,128,12,xin/HappyZcool-2016.ttf",
    "小可黄油体,Regular,butter,128,12,xin/butter.ttf",
    "沐瑶软笔手写体,Regular,Muyao-Softbrush,128,12,xin/Muyao-Softbrush.ttf",
    "贤二体,Regular,XianErTi,128,12,xin/XianErTi.ttf",
    "庞门正道轻松体,Regular,Pangmenzhengdaoqingsongti,128,12,xin/Pangmenzhengdaoqingsongti.ttf",
    "庞门正道粗书体,Regular,PangMenZhengDao-Cu,128,12,xin/PangMenZhengDao-Cu.ttf",
    "庞门正道标题体,Regular,PangMenZhengDao,128,12,xin/PangMenZhengDao.ttf",
    "江西拙楷,Regular,jiangxizhuokai-Regular,128,12,xin/jiangxizhuokai-Regular.ttf",
    "胡晓波真帅体,Regular,HuXiaoBo-ZhenShuai,128,12,xin/HuXiaoBo-ZhenShuai.ttf",
    "胡晓波男神体,Regular,HuXiaoBo-NanShen,128,12,xin/HuXiaoBo-NanShen.ttf",
    "胡晓波骚包体,Regular,HuXiaoBao-SaoBao,128,12,xin/HuXiaoBao-SaoBao.ttf",
    "钟齐志莽行书,Regular,ZhiMangXing-Regular,128,12,xin/ZhiMangXing-Regular.ttf",
    "手书体,Regular,ShouShuti,128,12,xin/ShouShuti.ttf",
    "清松手写体,Regular,JasonWriting,128,12,xin/JasonWriting.ttf",
    "品如手写体,Regular,Pinru,128,12,xin/Pinru.ttf",
    "卓健橄榄简体,Regular,ZhuoJianGanLanJianTi-Regular,128,12,xin/ZhuoJianGanLanJianTi-Regular.ttf",
    "联盟起艺卢帅正锐黑体,Regular,lianmengqiyilushuaizhengruiheiti-Regular,128,12,xin/lianmengqiyilushuaizhengruiheiti-Regular.ttf",
    "黄令东齐伋体,Regular,QIJIFALLBACK,128,12,xin/QIJIFALLBACK.ttf",
    "阿朱泡泡体,Regular,AZPPT_1_1436212_19,128,12,xin/AZPPT_1_1436212_19.ttf",
    "濑户字体,Regular,SetoFont,128,12,xin/SetoFont.ttf",
    "寒蝉手拙体,Regular,HCSZT-Regular,128,12,xin/HCSZT-Regular.ttf",
    "素材集市康康体,Regular,sucaijishikangkangti,128,12,xin/sucaijishikangkangti.ttf",
    "杨任东竹石体,Bold,YRDZST-Semibold,128,12,,xin/YRDZST-Semibold.ttf",
    "字体圈欣意冠黑体,Regular,Fontquan-XinYiGuanHeiTi-Regular,128,12,xin/Fontquan-XinYiGuanHeiTi-Regular.ttf",
    "悠然小楷,Regular,slideyouran-Regular,128,12,xin/slideyouran-Regular.ttf",
    "佛系体,Regular,Slidefu-Regular,128,12,xin/Slidefu-Regular.ttf",
    "鸿雷板书简体,Regular,HongLei-Regular,128,12,xin/HongLei-Regular.ttf",
    "峰广明锐体,Regular,fengguangmingrui,128,12,xin/fengguangmingrui.ttf",
    "站酷妙典风云体,Regular,Zcool-MiaoDianFengYun,128,12,xin/Zcool-MiaoDianFengYun.ttf",
    "站酷妙典和风体,Regular,Zcool-MiaoDianHeFeng,128,12,xin/Zcool-MiaoDianHeFeng.ttf",
    "站酷彤彤体,Regular,ZCOOLtongtong,128,12,xin/ZCOOLtongtong.ttf",
    "站酷型丽体  ,Bold,ZCOOLxintliti-Bold,128,12,xin/ZCOOLxintliti-Bold.ttf",
    "Zcool-LengShuiXiaoQingKeGuDianTi,Regular,Zcool-LengShuiXiaoQingKeGuDianTi-Regular,128,12,xin/Zcool-LengShuiXiaoQingKeGuDianTi-Regular.ttf",
    "叶根友微刚,Regular,ygyweigang,128,12,xin/ygyweigang.ttf",
    "叶根友唐楷简,Regular,yegenyou_tangkai,128,12,xin/yegenyou_tangkai.ttf",
    "叶根友特隶简体,Regular,yegenyou_teli,128,12,xin/yegenyou_teli.ttf",
    "叶根友毛笔行书,Regular,YeGenYouMaoBiXinShu2.1,128,12,xin/YeGenYouMaoBiXinShu2.1.ttf",
    "叶根友古刻体,Regular,YGYGUKETI,128,12,xin/YGYGUKETI.ttf",
    "南构孙策怒潮楷,Regular,NGsuncenuchaokai,128,12,xin/NGsuncenuchaokai.ttf",
    "南构日系楷行,Regular,NGrixikaixing,128,12,xin/NGrixikaixing.ttf",
    "南构拿朵手写,Regular,NGnaduoshouxie,128,12,xin/NGnaduoshouxie.ttf",
    "南构龙硬碑,Regular,NGlongyingbei,128,12,xin/NGlongyingbei.ttf",
    "南构刘志文新楷,Regular,NGliuzhiwenxinkai,128,12,xin/NGliuzhiwenxinkai.ttf",
    "南构黑洞体,Regular,NGheidong201904,128,12,xin/NGheidong201904.ttf",
    "三极魏碑简体,Regular,SJweibei-Regular,128,12,xin/SJweibei-Regular.ttf",
    "三极花信简体,Regular,SJhuaxin-Regular,128,12,xin/SJhuaxin-Regular.ttf",
    "三极竹枝简体,Regular,SJzhuzhi-Regular,128,12,xin/SJzhuzhi-Regular.ttf",
    "三极宜修简体,Regular,SJyixiu-Regular,128,12,xin/SJyixiu-Regular.ttf",
    "三极真喵空心简体,Regular,SJzhenmiaokongxin-Regular,128,12,xin/SJzhenmiaokongxin-Regular.ttf",
    "三极瑚琏简体,Regular,SJhulian-Regular,128,12,xin/SJhulian-Regular.ttf",
    "三极流金简体,Regular,SJliujin-Regular,128,12,xin/SJliujin-Regular.ttf",
    "三极则木简体,Regular,SJzemu-Regular,128,12,xin/SJzemu-Regular.ttf",
    "三极黄艺明书体,Regular,SJhym-Regular,128,12,xin/SJhym-Regular.ttf",
    "三极崇德行楷,Regular,SJchongdexingkai-Regular,128,12,xin/SJchongdexingkai-Regular.ttf",
    "三极猪猪静静,Regular,SJzhuzhujingjing-Regular,128,12,xin/SJzhuzhujingjing-Regular.ttf",
    "三极象形简体,Regular,SJxiangxing-Regular,128,12,xin/SJxiangxing-Regular.ttf",
    "三极行书简体,Regular,SJxingshu-Regular,128,12,xin/SJxingshu-Regular.ttf",
    "三极柳书简,Regular,SJliushu-Regular,128,12,xin/SJliushu-Regular.ttf",
    "三极拙楷简体,Regular,SJzhuokai-Regular,128,12,xin/SJzhuokai-Regular.ttf",
    "三极榜书简体,Regular,SJbangshujianti-Regular,128,12,xin/SJbangshujianti-Regular.ttf",
    "三极春联字体简,Regular,SJchunlian-Regular,128,12,xin/SJchunlian-Regular.ttf",
    "三极秦韵小篆,Regular,SJqinyunxiaozhuan-Regular,128,12,xin/SJqinyunxiaozhuan-Regular.ttf",
    "三极隶书简体,Regular,SJlishu-Regular,128,12,xin/SJlishu-Regular.ttf",
    " 三极砖隶简体,Regular,SJzhuanli-Regular,128,12,xin/SJzhuanli-Regular.ttf",
    "三极古圆简体,Regular,SJguyuan-Regular,128,12,xin/SJguyuan-Regular.ttf",
    "三极信黑简体,Regular,SJxinhei-Regular,128,12,xin/SJxinhei-Regular.ttf",
    "三极正极黑简体,Regular,SJzhengjihei-Regular,128,12,xin/SJzhengjihei-Regular.ttf",
    "三极正智黑简体,Regular,SJzhengzhihei-Regular,128,12,xin/SJzhengzhihei-Regular.ttf",
    "三极礼黑细简体,Regular,SJlihei-Regular,128,12,xin/SJlihei-Regular.ttf",
    "三极戟黑简体,Regular,SJjiheijianti-Regular,128,12,xin/SJjiheijianti-Regular.ttf",
    "三极仿宋简体,Regular,SJfangsong-Regular,128,12,xin/SJfangsong-Regular.ttf",
    "三极古宋简体,Regular,SJgusong-Regular,128,12,xin/SJgusong-Regular.ttf",
    "三极瘦金简体,Regular,SJshoujin-Regular,128,12,xin/SJshoujin-Regular.ttf",
    "三极博宋简体,Regular,SJbosong-Regular,128,12,xin/SJbosong-Regular.ttf",
    "三极典宋简体,Regular,SJdiansong-Regular,128,12,xin/SJdiansong-Regular.ttf",
    "Special Elite,Regular,SpecialElite-Regular,128,12,xin/SpecialElite-Regular.ttf",
    "沐瑶随心手写体,Regular,MuyaoPleased,128,12,xin/MuyaoPleased.ttf",
    "素材集市酷方体,Regular,sucaijishikufangti,128,12,xin/sucaijishikufangti.ttf",
    "春风楷,Regular,Slidechunfeng-Regular,128,12,xin/Slidechunfeng-Regular.ttf",
    "秋鸿楷,Regular,Slideqiuhong-Regular,128,12,xin/Slideqiuhong-Regular.ttf",
    "夏行楷,Regular,Slidexiaxing-Regular,128,12,xin/Slidexiaxing-Regular.ttf",
    "字体传奇特战体,Regular,ziticqtezhanti,128,12,xin/ziticqtezhanti.ttf",
    "Zhi Mang Xing,,,128,,a",
    "DejaVu Sans,Book,a,73791,12,",
    ",Bold,,,,",
    ",Bold Oblique,,73759,,",
    ",Light ExtraLight,DejaVuSans-ExtraLight,8207,,",
    ",Oblique,,73759,,",
    "DejaVu Sans Condensed,Book,a,73791,,",
    ",Bold,,,,",
    ",Bold Oblique,,73759,,",
    ",Oblique,,,,",
    "DejaVu Sans Mono,Book,a,65583,,",
    ",Bold,,,,",
    ",Bold Oblique,,65551,,",
    ",Oblique,,,,",
    "DejaVu Serif,Book,a,73743,14,",
    ",Bold,,,,",
    ",Bold Italic,,,,",
    ",Italic,,,,",
    "DejaVu Serif Condensed,Book,a,,,",
    "Liberation Mono,Regular,a,8223,7,",
    ",Bold,,,,",
    ",Bold Italic,,,,",
    ",Italic,,,,",
    "Liberation Sans,Regular,a,,12,",
    ",Bold,,,,",
    ",Bold Italic,,,,",
    ",Italic,,,,",
    "Liberation Serif,Regular,a,,14,",
    ",Bold,,,,",
    ",Bold Italic,,,,",
    ",Italic,,,,",
    "Fondamento Regular,Regular,Fondamento-Regular,128,12,xin/Fondamento-Regular.ttf",
    ",Italic,Fondamento-Italic,128,12,xin/Fondamento-Italic.ttf",
    "Amatic SC Regular,Regular,AmaticSC-Regular,128,12,xin/AmaticSC-Regular.ttf",
    ",Bold,AmaticSC-Bold,128,12,xin/AmaticSC-Bold.ttf",
    "Anton,Regular,Anton-Regular,128,12,xin/Anton-Regular.ttf",
    "Bangers,Regular,Bangers-Regular,128,12,xin/Bangers-Regular.ttf",
    "Barlow Condensed Regular,Regular,BarlowCondensed-Regular,128,12,xin/BarlowCondensed-Regular.ttf",
    ",Italic,BarlowCondensed-Italic,128,12,xin/BarlowCondensed-Italic.ttf",
    ",Medium,BarlowCondensed-Medium,128,12,xin/BarlowCondensed-Medium.ttf",
    ",MediumItalic,BarlowCondensed-MediumItalic,128,12,xin/BarlowCondensed-MediumItalic.ttf",
    ",Bold,BarlowCondensed-Bold,128,12,xin/BarlowCondensed-Bold.ttf",
    ",BoldItalic,BarlowCondensed-BoldItalic,128,12,xin/BarlowCondensed-BoldItalic.ttf",
    ",ExtraBold,BarlowCondensed-ExtraBold,128,12,xin/BarlowCondensed-ExtraBold.ttf",
    ",ExtraBoldItalic,BarlowCondensed-ExtraBoldItalic,128,12,xin/BarlowCondensed-ExtraBoldItalic.ttf",
    ",Black,BarlowCondensed-Black,128,12,xin/BarlowCondensed-Black.ttf",
    ",BlackItalic,BarlowCondensed-BlackItalic,128,12,xin/BarlowCondensed-BlackItalic.ttf",
    "Caveat Regular,Regular,Caveat-Regular,128,12,xin/Caveat-Regular.ttf",
    ",Bold,Caveat-Bold,128,12,xin/Caveat-Bold.ttf",
    "Creampuff,Regular,Creampuff,128,12,xin/Creampuff.ttf",
    "Damion,Regular,Damion,128,12,xin/Damion.ttf",
    "EB Garamond,Regular,EBGaramond-Regular,128,12,xin/EBGaramond-Regular.ttf",
    ",Italic,EBGaramond-Italic,128,12,xin/EBGaramond-Italic.ttf",
    ",Medium,EBGaramond-Medium,128,12,xin/EBGaramond-Medium.ttf",
    ",MediumItalic,EBGaramond-MediumItalic,128,12,xin/EBGaramond-MediumItalic.ttf",
    ",SemiBold,EBGaramond-SemiBold,128,12,xin/EBGaramond-SemiBold.ttf",
    ",SemiBoldItalic,EBGaramond-SemiBoldItalic,128,12,xin/EBGaramond-SemiBoldItalic.ttf",
    ",Bold,EBGaramond-Bold,128,12,xin/EBGaramond-Bold.ttf",
    ",BoldItalic,EBGaramond-BoldItalic,128,12,xin/EBGaramond-BoldItalic.ttf",
    ",ExtraBold,EBGaramond-ExtraBold,128,12,xin/EBGaramond-ExtraBold.ttf",
    ",ExtraBoldItalic,EBGaramond-ExtraBoldItalic,128,12,xin/EBGaramond-ExtraBoldItalic.ttf",
    "Gamja Flower,Regular,GamjaFlower-Regular,128,12,xin/GamjaFlower-Regular.ttf",
    "Indie Flower,Regular,IndieFlower,128,12,xin/IndieFlower.ttf",
    "Libre Baskerville,Regular,LibreBaskerville-Regular,128,12,xin/LibreBaskerville-Regular.ttf",
    ",Italic,LibreBaskerville-Italic,128,12,xin/LibreBaskerville-Italic.ttf",
    ",Bold,LibreBaskerville-Bold,128,12,xin/LibreBaskerville-Bold.ttf",
    "Merriweather Regular,Regular,Merriweather-Regular,128,12,xin/Merriweather-Regular.ttf",
    ",Light,Merriweather-Light,128,12,xin/Merriweather-Light.ttf",
    ",LightItalic,Merriweather-LightItalic,128,12,xin/Merriweather-LightItalic.ttf",
    ",Bold,Merriweather-Bold,128,12,xin/Merriweather-Bold.ttf",
    ",BoldItalic,Merriweather-BoldItalic,128,12,xin/Merriweather-BoldItalic.ttf",
    ",Black,Merriweather-Black,128,12,xin/Merriweather-Black.ttf",
    ",BlackItalic,Merriweather-BlackItalic,128,12,xin/Merriweather-BlackItalic.ttf",
    ",Italic,Merriweather-Italic,128,12,xin/Merriweather-Italic.ttf",
    "Monoton,Regular,Monoton-Regular,128,12,xin/Monoton-Regular.ttf",
    "Oleo Script Regular,Regular,OleoScript-Regular,128,12,xin/OleoScript-Regular.ttf",
    ",Bold,OleoScript-Bold,128,12,xin/OleoScript-Bold.ttf",
    "Permanent Marker,Regular,PermanentMarker-Regular,128,12,xin/PermanentMarker-Regular.ttf",
    "Playfair Display Regular,Regular,PlayfairDisplay-Regular,128,12,xin/PlayfairDisplay-Regular.ttf",
    ",Italic,PlayfairDisplay-Italic,128,12,xin/PlayfairDisplay-Italic.ttf",
    ",Bold,PlayfairDisplay-Bold,128,12,xin/PlayfairDisplay-Bold.ttf",
    ",BoldItalic,PlayfairDisplay-BoldItalic,128,12,xin/PlayfairDisplay-BoldItalic.ttf",
    ",Black,PlayfairDisplay-Black,128,12,xin/PlayfairDisplay-Black.ttf",
    ",BlackItalic,PlayfairDisplay-BlackItalic,128,12,xin/PlayfairDisplay-BlackItalic.ttf",
    "Roboto Thin,Regular,Roboto-Thin,128,12,xin/Roboto-Thin.ttf",
    ",Italic,Roboto-ThinItalic,128,12,xin/Roboto-ThinItalic.ttf",
    ",Light,Roboto-Light,128,12,xin/Roboto-Light.ttf",
    ",LightItalic,Roboto-LightItalic,128,12,xin/Roboto-LightItalic.ttf",
    "Roboto Regular,Regular,Roboto-Regular,128,12,xin/Roboto-Regular.ttf",
    ",Italic,Roboto-Italic,128,12,xin/Roboto-Italic.ttf",
    ",Medium,Roboto-Medium,128,12,xin/Roboto-Medium.ttf",
    ",MediumItalic,Roboto-MediumItalic,128,12,xin/Roboto-MediumItalic.ttf",
    ",Bold,Roboto-Bold,128,12,xin/Roboto-Bold.ttf",
    ",BoldItalic,Roboto-BoldItalic,128,12,xin/Roboto-BoldItalic.ttf",
    ",Black,Roboto-Black,128,12,xin/Roboto-Black.ttf",
    ",BlackItalic,Roboto-BlackItalic,128,12,xin/Roboto-BlackItalic.ttf",
    "Shrikhand,Regular,Shrikhand-Regular,128,12,xin/Shrikhand-Regular.ttf",
    "Titan One,Regular,TitanOne,128,12,xin/TitanOne.ttf",
    "Ultra,Regular,Ultra-Regular,128,12,xin/Ultra-Regular.ttf",
    "Sacramento,Regular,Sacramento-Regular,128,12,xin/Sacramento-Regular.ttf",
    "Trade Winds,Regular,TradeWinds,128,12,xin/TradeWinds.ttf",
    "UnifrakturMaguntia,Regular,UnifrakturMaguntia,128,12,xin/UnifrakturMaguntia.ttf",
    "Rye,Regular,Rye-Regular,128,12,xin/Rye-Regular.ttf",
    "Pinyon Script,Regular,PinyonScript,128,12,xin/PinyonScript.ttf",
    "Pacifico,Regular,Pacifico-Regular,128,12,xin/Pacifico-Regular.ttf",
    "Mrs Sheppards,Regular,MrsSheppards-Regular,128,12,xin/MrsSheppards-Regular.ttf",
    "Monsieur La Doulaise,Regular,MonsieurLaDoulaise-Regular,128,12,xin/MonsieurLaDoulaise-Regular.ttf",
    "Just Another Hand,Regular,JustAnotherHand-Regular,128,12,xin/JustAnotherHand-Regular.ttf",
    "Cinzel Decorative Regular,Regular,CinzelDecorative-Regular,128,12,xin/CinzelDecorative-Regular.ttf",
    ",Bold,CinzelDecorative-Bold,128,12,xin/CinzelDecorative-Bold.ttf",
    ",Black,CinzelDecorative-Black,128,12,xin/CinzelDecorative-Black.ttf",
    "Abril Fatface,Regular,AbrilFatface-Regular,128,12,xin/AbrilFatface-Regular.ttf",
    "!PaulMaul,Regular,a,1,6,",
    "20 db,Regular,a,8,4,",
]

from concurrent.futures import thread
import time
import requests

# API的基本URL
base_url = "https://ps.com/rsrc/fonts/"

# 遍历字体列表
for a in ttf:
    font_mapping = a.split(",")[5]
    # 构造API请求URL
    url = f"{base_url}{font_mapping}"

    # 发送GET请求
    response = requests.get(url)
    # 检查请求是否成功
    if response.status_code == 200:
        # 获取文件名
        file_name = f"getterFonts/{font_mapping}"  # 假设字体文件的扩展名为.ttf

        # 将文件保存到本地
        with open(file_name, "wb") as file:
            file.write(response.content)
        print(f"Font file for {font_mapping} saved successfully.")
    else:
        print(
            f"Failed to retrieve font file for {font_mapping}. Status code: {response.status_code}"
        )
        print(url)
